project:
  type: website

website:
  title: "栗子杯 LIZI CUP"
  navbar:
    left:
      - text: "基础规则"
        menu:
          - text: "基本"
            href: "基础规则/基本/基本.qmd"
          - text: "支援卡"
            href: "基础规则/支援卡/支援卡.qmd"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Slate
    include-css:
      - https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css
      - https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/slate/bootstrap.min.css
    include-js:
      - https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js
    toc: true
    fontsize: 0.9em
    linestretch: 1.6
    light: flatly
    dark: darkly
editor: visual
