project:
  type: website

website:
  title: "栗子杯 LIZI CUP"
  navbar:
    left:
      - text: "基础规则 Rule"
        menu:
          - text: "基本 Basic"
            href: "基础规则 Rule/基本 Basic/基本 Basic.qmd"
          - text: "支援卡 Support Card"
            href: "基础规则 Ruel/支援卡 Support Card/支援卡 Support Card.qmd"
    right:
      - href: 主页 Home.qmd
        text: 主页 Home
      - 背景 about.qmd

format:
  html:
    theme: Slate
    include-css:
      - https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css
      - https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/slate/bootstrap.min.css
    include-js:
      - https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js
    toc: true
    fontsize: 0.9em
    linestretch: 1.6
    light: flatly
    dark: darkly
editor: visual
