project:
  type: website

website:
  title: "栗子杯"
  navbar:
    left:
      - text: "报名教程"
        href: "报名教程/报名教程.qmd"
      - text: "基础规则"
        menu:
          - text: "基本"
            href: "基础规则/基本/基本.qmd"
          - text: "支援卡"
            href: "基础规则/支援卡/支援卡.qmd"
          - text: "禁卡表"
            href: "基础规则/禁卡表/禁卡表.qmd"
      - text: "历届出轮"
        href: "历届出轮"
        
    right:
      - href: "更多信息.qmd"
        text: "更多"
        

format:
  html:
    theme:
      light: cosmo
    toc: true
    fontsize: 1 em
    linestretch: 1.6
    backgroundcolor: Ivory
    light: flatly
editor: visual
