project:
  type: website

website:
  title: "栗子杯"
  navbar:
    left:
      - text: "报名教程"
        href: "报名教程/报名教程.qmd"
      - text: "基础规则"
        menu:
          - text: "比赛基本规则"
            href: "基础规则/基本/基本.qmd"
          - text: "支援卡"
            href: "基础规则/支援卡/支援卡.qmd"
          - text: "禁卡表"
            href: "基础规则/禁卡表/禁卡表.qmd"
      - text: "常见问题"
        menu:
          - text: "Steam非重下安装方法"
            href: "常见问题/Steam非重下安装方法.qmd"
          - text: "手机/Steam端数据引继"
            href: "常见问题/手机端数据引继.qmd"
          - text: "Q&A"
            href: "常见问题/Q&A.qmd"
            
    right:
      - href: "历届战报/历届战报.qmd"
        text: "历届战报"
      - href: "账号公布/账号公布.qmd"
        text: "账号公布"
      - href: "更多/更多.qmd"
        text: "更多"
        

format:
  html:
    theme:
      light: cosmo
    toc: true
    fontsize: 1 em
    linestretch: 1.6
    backgroundcolor: Ivory
    light: flatly
editor: visual
